### ISSUE TITLE
Cuts tags

### ISSUE THREAD

**Issue by luminatee** [MrSaints/Morphext#1]
Hi. When I use Morphext for element, he cuts all html tags exept plain text. How I can disable it?

**Comment by dangelion** [comment]
I just opened this issue https://github.com/MrSaints/Morphext/issues/13

Have you implemented this feature? Like an option cutHtml:true/false ?

If not do you intend to do it or it's better I search for something else?

It makes sense to use Morphist in place of this, only because of the "html cut" problem?

**Comment by MrSaints** [comment]
@dangelion, as my previous posts stated, I don't intend on implementing this for Morphext. It's meant to be simple. I strongly recommend you look into Morphist or consider forking this project, and making the changes I mentioned in https://github.com/MrSaints/Morphext/issues/1#issuecomment-56539171 (i.e. text to html fn).
