### ISSUE TITLE
The latest version tag problem

### ISSUE THREAD

**Issue by nolsherry** [MrSaints/Morphext#20]
Hi @MrSaints , I am the member of [cdnjs](https://github.com/cdnjs/cdnjs), and we wants to host this repository. However, I found that that the latest  version tag about this repository is `v2.2.1`, but it seemed that the latest version is `2.4.7` according to the [package.json](https://github.com/MrSaints/Morphext/blob/master/package.json) file. 
Could you help me update the version tag? Thanks!
![image](https://cloud.githubusercontent.com/assets/8747900/21181580/9af71af6-c239-11e6-989d-d95136e0ebe8.png)

cdnjs/cdnjs#9219

**Comment by MrSaints** [comment]
The latest release is actually `2.4.4` (https://github.com/MrSaints/Morphext/releases). The `v2.2.1` should have been `2.2.1` (without the `v`).

Master is on `2.4.7`, but I don't think it matters that much since the changes have mostly been on the dev side. That is, it does not affect the compiled code.

I'm happy to release the most up-to-date version anyway 👍 Let me know if there's anything else I need to do to get it to work with cdnjs.

Thanks!

**Comment by MrSaints** [comment]
Hi @maruilian11 @nolsherry @filipsedivy, I'm awaiting your response on this. I'll be closing this issue off in the coming weeks if it goes unanswered. Thanks!

**Comment by maruilian11** [comment]
Hi @MrSaints, sorry for the late reply.
If you think it's ok to not host `2.4.7` on cdnjs, I think we can close this issue.
We only need you to help keep releasing up-to-date tags which will affect the compile code 👍 Thank you!

**Comment by MrSaints** [comment]
Hi @maruilian11, yes, I'm okay with `2.4.4` being released on cdnjs. I'm assuming once I release a new tag it will update automatically on cdnjs?

**Comment by maruilian11** [comment]
@MrSaints Yes, our bot will update it in few hours after you release. 👍

**Comment by MrSaints** [comment]
@maruilian11 Great! Well, let me know if there's anything you need me to do / help with 😄 Thanks!
